bag/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

gifts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_gifts, name='gifts'),
    path('gift/<int:gift_id>/', views.gift_detail, name='gift_detail'),
    path('add/', views.add_gift, name='add_gift'),
    path('edit/<int:gift_id>/', views.edit_gift, name='edit_gift'),
    path('delete/<int:gift_id>/', views.delete_gift, name='delete_gift'),
]

my_gifted_moments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('home.urls')),
    path('gifts/', include('gifts.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('favorites/', include('favorites.urls')),
    path('faq/', include('faq.urls')),
    path('contact/', include('contact.urls')),
    path('newsletter/', include('newsletter.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # noqa


handler404 = 'my_gifted_moments.views.handler404'

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from gifts.models import Gift
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True, related_name='orders')  # noqa
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(max_digits=6, decimal_places=2, null=False, default=0)  # noqa
    order_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)  # noqa
    grand_total = models.DecimalField(max_digits=10, decimal_places=2, null=False, default=0)  # noqa

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0  # noqa
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100  # noqa
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False, on_delete=models.CASCADE, related_name='lineitems')  # noqa
    gift = models.ForeignKey(Gift, null=False, blank=False, on_delete=models.CASCADE)  # noqa
    gift_size = models.CharField(max_length=2, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, editable=False)  # noqa

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.gift.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.order.order_number}'

gifts/models.py
from django.db import models
from cloudinary.models import CloudinaryField


class Occasion(models.Model):
    """ Custom model for occasions: wedding, baby shower, etc. """
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Size(models.Model):
    """ Custom model for sizes: small, medium, large, etc. """
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Gift(models.Model):
    """ Custom model for gifts. """
    name = models.CharField(max_length=255, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    occasion = models.ForeignKey(Occasion, on_delete=models.CASCADE, related_name="gifts_by_occasion")  # noqa
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="gifts_by_category")  # noqa
    size = models.ForeignKey(Size, on_delete=models.CASCADE, related_name="gifts_by_size")  # noqa
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)  # noqa
    image = CloudinaryField("image", default="placeholder", null=False, blank=False)  # noqa

    def __str__(self):
        return f"{self.category.name}: {self.name}"

gifts/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Gift, Category


class GiftForm(forms.ModelForm):

    class Meta:
        model = Gift
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False, widget=CustomClearableFileInput)  # noqa

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-dark rounded-0'

gifts/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Gift, Category, Occasion
from favorites.models import Favorite
from .forms import GiftForm


def all_gifts(request):
    """ A view to show all gifts, including sorting and search queries """
    gifts = Gift.objects.all()
    query = None
    current_categories = None
    current_occasions = None
    sort = None
    direction = None

    if 'sort' in request.GET:
        sortkey = request.GET['sort']
        sort = sortkey
        if sortkey == 'name':
            gifts = gifts.annotate(lower_name=Lower('name'))
            sortkey = 'lower_name'
        elif sortkey == 'category':
            sortkey = 'category__name'
        elif sortkey == 'price':
            sortkey = 'price'

        if 'direction' in request.GET:
            direction = request.GET['direction']
            if direction == 'desc':
                sortkey = f'-{sortkey}'
        gifts = gifts.order_by(sortkey)
    if 'occasion' in request.GET:
        occasion_names = request.GET['occasion'].split(',')
        gifts = gifts.filter(occasion__name__in=occasion_names)
        current_occasions = Occasion.objects.filter(name__in=occasion_names)

    if 'category' in request.GET:
        category_names = request.GET['category'].split(',')
        gifts = gifts.filter(category__name__in=category_names)
        current_categories = Category.objects.filter(name__in=category_names)
    if 'q' in request.GET:
        query = request.GET['q']
        if not query:
            messages.error(request, "You didn't enter any search criteria!")
            return redirect(reverse('gifts'))

        queries = Q(name__icontains=query) | Q(description__icontains=query)
        gifts = gifts.filter(queries)

    current_sorting = f'{sort}_{direction}'
    context = {
        'gifts': gifts,
        'search_term': query,
        'current_categories': current_categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'gifts/gift_list.html', context)
    print("Current sorting:", current_sorting)


def gift_detail(request, gift_id):
    gift = get_object_or_404(Gift, pk=gift_id)

    is_favorited = False
    if request.user.is_authenticated:
        is_favorited = Favorite.objects.filter(user=request.user, gift=gift).exists()  # noqa

    context = {
        'gift': gift,
        'is_favorited': is_favorited,
    }
    return render(request, 'gifts/gift_detail.html', context)


@login_required
def add_gift(request):
    """ Add a gift to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = GiftForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully added gift!')
            return redirect(reverse('add_gift'))
        else:
            messages.error(request, 'Failed to add gift. Please ensure the form is valid.')  # noqa
    else:
        form = GiftForm()
    template = 'gifts/add_gift.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_gift(request, gift_id):
    """ Edit a gift in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    gift = get_object_or_404(Gift, pk=gift_id)
    if request.method == 'POST':
        form = GiftForm(request.POST, request.FILES, instance=gift)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated gift!')
            return redirect(reverse('gift_detail', args=[gift.id]))
        else:
            messages.error(
                request,
                'Failed to update gift. Please ensure the form is valid.')
    else:
        form = GiftForm(instance=gift)
        messages.info(request, f'You are editing {gift.name}')

    template = 'gifts/edit_gift.html'
    context = {
        'form': form,
        'gift': gift,
    }

    return render(request, template, context)


@login_required
def delete_gift(request, gift_id):
    """ Delete a gift from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    gift = get_object_or_404(Gift, pk=gift_id)
    gift.delete()
    messages.success(request, 'Gift deleted!')
    return redirect(reverse('gifts'))

gifts/templates/gifts/add_gift.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container ">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container mb-5">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Gift Management</h2>
                <h5 class="text-muted">Add a Gift</h5>
                <hr>
            </div>
        </div>

        <!-- Add Gift Form -->
        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST"
                      action="{% url 'add_gift' %}"
                      enctype="multipart/form-data"
                      class="form mb-2">
                    {% csrf_token %}
                    {{ form|crispy }}
                    
                    <div class="text-right mt-3">
                        <a href="{% url 'gifts' %}" class="btn btn-outline-dark rounded-0">Cancel</a>
                        <button type="submit" class="btn btn-success rounded-0">Add Gift</button>
                    </div>
                </form>
            </div>
        </div>
        
    </div>
{% endblock %}

gifts/templates/gifts/edit_gift.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container ">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <!-- Page Title -->
        <div class="row">
            <div class="col-12 col-md-6">
                <hr>
                <h2 class="logo-font mb-4">Gift Management</h2>
                <h5 class="text-muted">Edit a Gift</h5>
                <hr>
            </div>
        </div>

        <!-- Edit Gift Form -->
        <div class="row">
            <div class="col-12 col-md-6">
                <form method="POST"
                      action="{% url 'edit_gift' gift.id %}"
                      enctype="multipart/form-data"
                      class="form mb-2">
                    {% csrf_token %}
                    
                    {% for field in form %}
                        {% if field.name != 'image' %}
                            {{ field|as_crispy_field }}
                        {% else %}
                            {{ field }}
                        {% endif %}
                    {% endfor %}

                    <div class="text-right mt-3">
                        <a href="{% url 'gifts' %}" class="btn btn-outline-black rounded-0">Cancel</a>
                        <button type="submit" class="btn btn-dark rounded-0">Update Item</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $('#new-image').change(function () {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

gifts/templates/gifts/gift_detail.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">

{% block page_header %}
<div class="container ">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <!-- Gift Image -->
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container my-5">
                {% if gift.image %}
                <a href="{{ gift.image.url }}" target="_blank">
                    <img src="{{ gift.image.url }}" alt="{{ gift.name }}" class="card-img-top gift-img-detail">
                </a>
                {% else %}
                <a href="#">
                    <img src="{{ MEDIA_URL }}noimage.png" alt="{{ gift.name }}" class="card-img-top gift-img-detail">
                </a>
                {% endif %}
            </div>
        </div>

        <!-- Gift Details -->
        <div class="col-12 col-md-6 col-lg-4">
            <div class="gift-details-container mb-5 mt-md-5">
                <h2 class="mb-0">{{ gift.name }}</h2>
                <p class="lead mb-0 text-left font-weight-bold">${{ gift.price }}</p>

                {% if gift.category %}
                <p class="small mt-1 mb-0">
                    <a href="{% url 'gifts' %}?category={{ gift.category.name }}" class="text-muted">
                        <i class="fas fa-tag mr-1"></i>{{ gift.category.name }}
                    </a>
                </p>
                {% endif %}

                <p class="small mt-1 mb-0 text-muted">
                    Occasion: {{ gift.occasion.name }}<br>
                    Size: {{ gift.size.name }}<br>
                    In stock: {{ gift.quantity }}
                </p>

                <p class="mt-3">{{ gift.description }}</p>

                <!-- Add to Bag Form -->
                <form class="form" method="POST" action="{% url 'add_to_bag' gift.id %}">
                    {% csrf_token %}
                    <div class="form-row">
                        {% with gift.has_sizes as s %}
                        {% if s %}
                        <div class="col-12">
                            <p><strong>Size:</strong></p>
                            <select name="gift_size" id="id_gift_size" class="form-control rounded-0 w-50">
                                <option value="8pc">8pc.</option>
                                <option value="16pc">16pc.</option>
                                <option value="24pc" selected>24pc.</option>
                                <option value="36pc">36pc.</option>
                                <option value="48pc">48pc.</option>
                            </select>
                        </div>
                        {% endif %}

                        <!-- Quantity Controls -->
                        <div class="col-12">
                            <p class="mt-3"><strong>Quantity:</strong></p>
                            <div class="input-group input-group-sm">
                                <div class="input-group-prepend">
                                    <button class="decrement-qty btn btn-outline-secondary"
                                        data-item_id="{{ item.gift.id }}" id="decrement-qty_{{ item.gift.id }}">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                                <input type="number" name="quantity" value="1" min="1" max="99"
                                    id="id_qty_{{ item.gift.id }}" data-item_id="{{ item.gift.id }}"
                                    class="form-control qty_input">
                                <div class="input-group-append">
                                    <button class="increment-qty btn btn-outline-secondary"
                                        data-item_id="{{ item.gift.id }}" id="increment-qty_{{ item.gift.id }}">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </div>

                        <!-- Actions -->
                        <div class="col{% if s %}-12 mt-2{% endif %} d-flex align-items-center">
                            <a href="{% url 'gifts' %}" class="btn btn-outline-black rounded-0 mt-5">
                                <span class="icon"><i class="fas fa-chevron-left"></i></span>
                                <span class="text-uppercase">Keep Shopping</span>
                            </a>
                            <input type="submit" value="Add to Bag" class="btn btn-outline-dark rounded text-uppercase mt-5">
                            {% if user.is_authenticated %}
                            {% if is_favorited %}
                            <a href="{% url 'remove_from_favorites' gift.id %}?next={{ request.path }}" class="text-danger mt-5"
                                title="Remove from Favorites">
                                <i class="fas fa-heart fa-lg"></i>
                            </a>
                            {% else %}
                            <a href="{% url 'add_to_favorites' gift.id %}" class="text-muted mt-5" title="Add to Favorites">
                                <i class="far fa-heart fa-lg"></i>
                            </a>
                            {% endif %}
                            {% endif %}
                        </div>

                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        {% endwith %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'gifts/includes/quantity_input_script.html' %}
{% endblock %}

gifts/templates/gifts/gift_list.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">

{% block page_header %}
    <div class="container ">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container-fluid">
        <!-- Page Header -->
        <div class="row">
            <div class="col text-center mt-3">
                <h2 class="logo-font text-uppercase">Gifts</h2>

                {% for c in current_categories %}
                    <a href="{% url 'gifts' %}?category={{ c.name }}" class="category-badge text-decoration-none">
                        <span class="p-2 mt-2 badge badge-white text-dark rounded-0 border border-dark">
                            {{ c.friendly_name }}
                        </span>
                    </a>
                {% endfor %}

                <hr class="w-100 mb-1">
            </div>
        </div>

        <!-- Sort + Results -->
        <div class="row">
            <div class="col-10 offset-1">
                <div class="row mt-1 mb-2">
                    <div class="col-12 col-md-6 my-auto order-md-last d-flex justify-content-center justify-content-md-end">
                        <div class="sort-select-wrapper w-50">
                            <select id="sort-selector"
                                class="custom-select custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                                <option value="reset" {% if current_sorting == "None_None" %}selected{% endif %}>Sort by...</option>
                                <option value="price_asc" {% if current_sorting == "price_asc" %}selected{% endif %}>Price (low to high)</option>
                                <option value="price_desc" {% if current_sorting == "price_desc" %}selected{% endif %}>Price (high to low)</option>
                                <option value="name_asc" {% if current_sorting == "name_asc" %}selected{% endif %}>Name (A-Z)</option>
                                <option value="name_desc" {% if current_sorting == "name_desc" %}selected{% endif %}>Name (Z-A)</option>
                                <option value="category_asc" {% if current_sorting == "category_asc" %}selected{% endif %}>Category (A-Z)</option>
                                <option value="category_desc" {% if current_sorting == "category_desc" %}selected{% endif %}>Category (Z-A)</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-12 col-md-6 order-md-first">
                        <p class="text-muted mt-3 text-center text-md-start">
                            {% if search_term or current_categories or current_sorting != 'None_None' %}
                                <span class="small"><a href="{% url 'home' %}">Gifts Home</a> | </span>
                            {% endif %}
                            {{ gifts|length }} Gift{{ gifts|length|pluralize }}{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
                        </p>
                    </div>
                </div>

                <!-- Gifts List -->
                <div class="row">
                    {% for gift in gifts %}
                    <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3 mb-4">
                        <div class="card h-100 border-0 shadow-sm">
                            <a href="{% url 'gift_detail' gift.id %}">
                                <img class="card-img-top gift-img" src="{{ gift.image.url }}" alt="{{ gift.name }}">
                            </a>
                            <div class="card-body pb-0">
                                <p class="mb-0 font-semibold">{{ gift.name }}</p>
                            </div>
                            <div class="card-footer bg-white pt-0 border-0 text-start">
                                <div class="row">
                                    <div class="col">
                                        <p class="lead mb-0 font-weight-bold">${{ gift.price }}</p>
                                        {% if gift.category %}
                                            <p class="small mt-1 mb-0">
                                                <a href="{% url 'gifts' %}?category={{ gift.category.name }}" class="text-muted">
                                                    <i class="fas fa-tag mr-1"></i>{{ gift.category.friendly_name }}
                                                </a>
                                            </p>
                                        {% endif %}
                                        {% if request.user.is_superuser %}
                                            <small class="ml-3">
                                                <a href="{% url 'edit_gift' gift.id %}">Edit</a> |
                                                <a href="{% url 'delete_gift' gift.id %}" class="text-danger">Delete</a>
                                            </small>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <!-- Back to Top Button -->
    <button id="btt-btn" class="btn btt-btn shadow rounded-circle">
        <i class="fas fa-chevron-up"></i>
    </button>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script type="text/javascript">
        $(window).scroll(function () {
            if ($(this).scrollTop() > 100) {
                $('#btt-btn').fadeIn();
            } else {
                $('#btt-btn').fadeOut();
            }
        });

        $('#btt-btn').click(function () {
            $('html, body').animate({ scrollTop: 0 }, 'smooth'); // Smooth scroll to top
        });

        $('#sort-selector').change(function () {
            const selector = $(this);
            const currentUrl = new URL(window.location);
            const selectedVal = selector.val();
            if (selectedVal !== "reset") {
                const [sort, direction] = selectedVal.split("_");
                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);
            } else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");
            }
            window.location.replace(currentUrl);
        });
    </script>
{% endblock %}